apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: download-data-files
  name: d2s-download-pod
  namespace: argo
spec:
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: data2services-storage
  containers:
  - name: d2s-download
    image: vemonet/d2s-download:latest
    command: [ "tail", "-f", "/dev/null"]
    #"--password", "$DOWNLOADPASSWORD" ] # TODO: secret not working
    # env:
    # - name: DOWNLOADPASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: d2s-download-password
    #       key: password
    volumeMounts:
    - name: workdir
      mountPath: /data