apiVersion: batch/v1
kind: Pod
metadata:
  labels:
    purpose: download-input-file
  name: d2s-download-pod
  namespace: argo
spec:
  containers:
  - name: d2s-download
    image: vemonet/data2services-download
    env:
    - name: dataset-to-download
      value: "pubmed"
    - name: working-path
      value: "/data/pubmed/input"
    args: ["--download-datasets", "$(dataset-to-download)", "--working-path", "$(working-path)"]
    volumeMounts:
    - mountPath: /data
      name: workdir
  restartPolicy: OnFailure
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: data2services-storage