apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: d2s-workflow-transform-csv-
spec:
  entrypoint: execute-workflow

  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: data2services-storage

  arguments:
    parameters:
    - name: datasetToProcess
      value: stitch             # 07:39 min when download files
    - name: downloadUsername
      value: my_download_username
    - name: tmpGraphUri
      value: https://w3id.org/data2services/graph/autor2rml
    - name: sparqlEndpoint
      value: http://node000002.cluster.ids.unimaas.nl/
    - name: sparqlRepository
      value: test
    - name: sparqlUsername
      value: import_user
    - name: sparqlPassword
      value: null
    - name: sparqlQueryMetadata
      value: null
    - name: sparqlQueryTransform
      value: null
    - name: sparqlBiolinkGraphUri
      value: https://w3id.org/data2services/graph/biolink
    - name: sparqlGenericRdfServiceUrl
      value: repository:test


  templates:
  - name: execute-workflow
    dag:
      tasks:
      - name: download-files
        template: d2s-download
      - name: drill
        template: apache-drill
      - name: run-autor2rml
        template: autor2rml
        dependencies: [drill, download-files]
        arguments:
          parameters:
          - name: jdbcUrl
            value: "jdbc:drill:drillbit={{tasks.drill.ip}}:31010"


  - name: d2s-download
    container:
      image: vemonet/data2services-download:latest
      args: [ "--download-datasets", "{{workflow.parameters.datasetToProcess}}", "--working-path", "/data/{{workflow.parameters.datasetToProcess}}/input",
      "--username", "{{workflow.parameters.downloadUsername}}"] 
      volumeMounts:
      - name: workdir
        mountPath: /data

  - name: apache-drill
    daemon: true                        # start influxdb as a daemon
    container:
      image: vemonet/apache-drill:latest
      volumeMounts:
        - name: workdir
          mountPath: /data # readonly?
      # readinessProbe:  # wait for readinessProbe to succeed
      #   httpGet:
      #     path: /
      #     port: 8047
      #   initialDelaySeconds: 5
        #timeoutSeconds: 1
      livenessProbe:
        tcpSocket:
          port: 8047
        initialDelaySeconds: 5
        timeoutSeconds: 1

  - name: autor2rml
    inputs:
      parameters:
      - name: jdbcUrl
    container:
      image: vemonet/autor2rml:latest
      args: ["-j", "{{inputs.parameters.jdbcUrl}}", 
      "-o", "/data/{{workflow.parameters.datasetToProcess}}/output/mapping.trig", "-d", "/data/{{workflow.parameters.datasetToProcess}}/input",
      "-b", "https://w3id.org/data2services/", "-g", "{{workflow.parameters.tmpGraphUri}}"]
      volumeMounts:
      - name: workdir
        mountPath: /data