apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: d2s-running-services
  name: d2s-pod-drill
  namespace: argo
spec:
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: data2services-storage
  containers:
  - name: d2s-drill
    image: vemonet/apache-drill:latest
    #command: [ "tail", "-f", "/dev/null"]
    volumeMounts:
    - name: workdir
      mountPath: /data