apiVersion: v1
kind: Pod
# https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html

metadata:
  labels:
    app: tensorflow-gpu
  name: pod-tensorflow-gpu
  namespace: test-vincent
spec:
  containers:
  - name: tensorflow-gpu
    image: tensorflow/tensorflow:latest-gpu-py3-jupyter
    restartPolicy: OnFailure
    resources:
      limits:
        nvidia.com/gpu: 1
    ports:
    - containerPort: 8888
      protocol: TCP
    volumeMounts:
    - name: workdir
      mountPath: /tf/notebooks
      subpath: tensorflow-gpu-remzi
  volumes:
    - name: workdir
      persistentVolumeClaim:
        claimName: pvc-mapr-projects-test-vincent